### ISSUE TITLE
TODO Examples

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#1]
These are some topics that need examples, but not I'm too familiar with. It would be great if someone more familiar with these topics could send a PR adding examples for these topics.

- [ ] Procedural macros #155
- [ ] `Any`
- [ ] `Arc` #104
- [ ] `Ascii`
- [ ] `Cell`
- [ ] `Gc`
- [ ] `Mutex` #105
- [ ] `Once`
- [ ] `Rc`
- [ ] `RefCell`
- [ ] `Unsafe<T>`
- [ ] `bitflags`
- [ ] `green` `#[start]` and `rustuv::event_loop` vs `basic::event_loop`
- [ ] `local_data`
- [ ] `log` crate
- [ ] `net::tcp`
- [ ] `rustdoc` #108

These are topics that I can cover, and some already appear in the book as unavailable. But I won't get angry if someone wants to give me a hand :-).

- [ ] Bottom types `!` #146
- [ ] FFI #114
- [ ] Phantom types #145
- [ ] `Barrier` #113
- [ ] `Buffered{Reader,Writer}`
- [ ] `assert!`, `debug_assert!`, etc.
- [ ] `macros_rules` #110
- [ ] `os::args` + `getopts` #106
- [ ] `rand` #116
- [ ] `regex` crate
- [ ] `select!`
- [ ] `serialize::json` #86
- [ ] `std::hash` + `collections::hashmap` #161
- [ ] `std::io::stdio`
- [ ] `term` crate
- [ ] `unsafe` blocks #112
- [ ] `url` crate
- [ ] bench #115
- [ ] closures #91
- [ ] comments: `//`, `/* */`, `/* /* */ */`, `///`, etc. #107
- [ ] formatting #196
- [ ] kinds: `Send`, `Share`, `Copy` and `Sized`
- [ ] raw pointers `*T` #112
- [ ] tasks #113
- [ ] testing #111
- [ ] unsafe global state (static mut) #112
- [x] `Drop`
- [x] `Process`
- [x] `Result` and `try!`
- [x] `std::io::fs`
- [x] attributes: `#[test]`, `#[crate_id]`, etc
- [x] file I/O
- [x] modules and crates
- [x] operator overloading: `Add`, `Sub`, etc.
- [x] simd

**Comment by kmcallister** [comment]
The official [plugins guide](http://doc.rust-lang.org/guide-plugin.html) has examples for procedural macros as well as lint plugins.

**Comment by steveklabnik** [comment]
I'm not going to track these kinds of things on the tracker. More examples are always welcome.
