### ISSUE TITLE
Cargo chapter tracking issue

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust-by-example#978]
This is a tracking issue for the various parts of the cargo chapter. I think I have a recent start, but there are some things that I don't have experience/knowledge of... Here is a checklist from @steveklabnik 's comment [here](https://github.com/rust-lang/rust-by-example/pull/949#issuecomment-345683651).

- [x] cargo build #949 
- [x] basic conventions of the top-level directories #949
- [ ] dependencies
    - [x] crates.io and deps for it #949
    - [x] git deps #949 
    - [x] path deps #949
    - [ ] override and patch or whatever the latest way to do this is, I forget which one
- [ ] workspaces
- [ ] profiles
- [ ] the -sys crate convention from a usage perspective, which leads you into:
- [ ] build scripts

**Comment by mark-i-m** [comment]
cc #215

**Comment by mark-i-m** [comment]
@marioidival Perhaps add the "help wanted" tag to this issue? I'm not knowledgeable enough to do the rest...

**Comment by marioidival** [comment]
@mark-i-m that label means the same thing...

**Comment by rusty-snake** [comment]
to do: Add `edition="2018"` to https://doc.rust-lang.org/stable/rust-by-example/cargo/deps.html

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
